language: php
php:
  - 7.4.3

cache:
  directories:
    - node_modules
    - vendor

notifications:
  email:
    recipients:
      - developer@parabola-solutions.com

deploy:
- provider: s3
  access_key_id: "AKIA4CIWM6RZVOGMM7XC"
  secret_access_key: "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"
  local_dir: dpl_cd_upload
  skip_cleanup: true
  on: &2
    repo: grahamblandford/iwd_lamp2
    branch: main
  bucket: lamp-bucket
  region: us-east-2
- provider: codedeploy
  access_key_id: "AKIA4CIWM6RZVOGMM7XC"
  secret_access_key: "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"
  bucket: lamp-bucket
  key: latest.zip
  bundle_type: zip
  application: lamp
  deployment_group: lamp
  region: us-east-2
  on: *2


script:
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip    